<div class="flex-grow flex items-center justify-center px-4 py-24">
    <div class="bg-gradient-to-r from-sky-400 via-sky-200 to-sky-50 w-full max-w-2xl min-h-[500px] p-12 rounded-[3rem] shadow-2xl border-white/50 flex flex-col justify-center">
    
    <div class="text-center mb-10">
        <div class="inline-flex items-center justify-center w-16 h-16 bg-white/40 rounded-2xl mb-4 shadow-sm">
            <span class="text-3xl">👻</span>
        </div>
        <h2 class="text-2xl font-bold tracking-tight">
            <span class="text-sky-900">Welcome </span>
            <span class="text-sky-900 drop-shadow-lg">To Do </span>
            <span class="text-white drop-shadow-lg">Ghost!</span>
        </h2>
        <p class="text-sky-700/80 text-sm font-medium hover:text-white transition-all duration-200">Tasks Made Easy To Disappear</p>
    </div>

    <div class="flex justify-center">
        <a href="/dashboard" 
           class="group relative inline-flex items-center justify-center px-10 py-3.5 font-bold text-white transition-all duration-200 bg-sky-700 rounded-xl hover:bg-sky-200 hover:shadow-lg">
            <span>Enter</span>
        </a>
    </div>

    </div>
</div>